version: "3"
services:
  test:
    build: ./
    image: test-xray-images
    container_name: test-xray-ps
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./:/root
    environment:
      - AUUID="4b1f8e62-57a7-4ac3-bd56-e3a40e139ac3"
      - CADDYIndexPage="https://raw.githubusercontent.com/caddyserver/dist/master/welcome/index.html"
      - CONFIGCADDY="https://raw.githubusercontent.com/8NEZNhg7U73i/322oRG748tZ2HENf/main/etc/Caddyfile"
      - CONFIGXRAY="https://raw.githubusercontent.com/8NEZNhg7U73i/322oRG748tZ2HENf/main/etc/xray.json"
      - ParameterSSENCYPT="AES-256-GCM"
    ports:
      - "10800:1080/tcp"
      - "10800:1080/udp"
      - "20800:80/tcp"
    restart: always
